apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mafia-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.mafia.game
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mafia-service
            port:
              number: 80
