server:
  port: 8080
  debug: false
database:
  url: ${DATABASE_URL}
redis:
  addr: redis:6379
rabbitmq:
  url: amqp://guest:guest@rabbitmq:5672/
payment:
  zarinpal: https://api.zarinpal.com/pg/v4/payment
webrtc:
  ice_servers:
    - urls: stun:stun.l.google.com:19302
logging:
  level: info
  format: json
